### ISSUE TITLE
[FEATURE REQUEST] support multiple NICs

### ISSUE THREAD

**Issue by nicholasmhughes** [salt-extensions/saltext-azurerm#11]
Copied from Salt issue 56153 opened by @tkykm
https://github.com/saltstack/salt/issues/56153#issue-564642759

**Is your feature request related to a problem? Please describe.**
It would be good to have a option about multiple NICs.
In some case, we want to associate a VM to 2 or more subnet e.g. frontend and backend

Thanks!

**Describe the solution you'd like**
Ideally profile
```
vm:
  provider: azure
  nics:
    - network: vnet1
       subnet: subnet1
    - network: vnet1
       subnet: subnet2
       security_group: sg1
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
