### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaveLafleur** [salt-extensions/saltext-azurerm#17]
**Description**
salt-cloud -m errors out based on an incomplete profile but does not indicate which attribute is missing a value.  

**Setup**
<details><summary>/etc/salt/cloud.providers.d/azure.conf</summary>
/etc/salt/cloud.providers.d/azure.conf

```
azure-config:
  driver: azurerm
  subscription_id: <subscription>
  certificate_path: /etc/salt/azure.pem
  tenant: <tenant>
  client_id: <client>
  secret: <secret>
  location: southcentralus

```
</details>

<details><summary>/etc/salt/cloud.profiles.d/azure.conf</summary>
/etc/salt/cloud.profiles.d/azure.conf

```
azure-ubuntu:
  provider: tt-azure-config
  image: 'canonical|0001-com-ubuntu-server-focal|20_04-lts-gen2|latest'
  size: Standard_D2s_v3
  location: 'southcentralus'
  ssh_username: azureuser
  ssh_publickeyfile: /etc/salt/saltkey.pub
  virtual_network_name: EnterpriseMgmt-vnet
  subnet_name: default
  slot: production
  resource_group_name: EnterpriseMgmt

```
</details>

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details (azure ubuntu)
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```
Salt Version:
            Salt: 3004.2

Dependency Versions:
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.7.3
       docker-py: Not Installed
           gitdb: 2.0.6
       gitpython: 3.0.7
          Jinja2: 2.10.1
         libgit2: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
         msgpack: 0.6.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: 3.6.1
          pygit2: Not Installed
          Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
    python-gnupg: 0.4.5
          PyYAML: 5.3.1
           PyZMQ: 18.1.1
           smmap: 2.0.5
         timelib: Not Installed
         Tornado: 4.5.3
             ZMQ: 4.3.2

Salt Extensions:
 saltext.azurerm: 1.0.0

System Versions:
            dist: ubuntu 20.04 focal
          locale: utf-8
         machine: x86_64
         release: 5.15.0-1020-azure
          system: Linux
         version: Ubuntu 20.04 focal```
</details>

**Additional context**
Add any other context about the problem here.
